version: "3.2"

services:
  # Database
  db:
    image: mysql:8
    container_name: dockertest5-mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1234
      MYSQL_DATABASE: docker_test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password1234
    ports:
      - 3306:3306
    networks:
      - backend

  # Custom image container
  web:
    depends_on:
      - db
    build:
      context: .
    image: jeffmlazo/docker-php-no-framework:1.0.0
    container_name: dockertest5-app
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www:/var/www/html
    environment:
      MYSQL_HOST: dockertest5-mysql
      MYSQL_DATABASE: docker_test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password1234
    ports:
      - 8000:80
      - 443:443
    networks:
      - frontend
      - backend

  # Database management tool
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: "pepa-linha"
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mysql:
